version: '3.8'
services: 
  database:
    image: mongo
    restart: always 
    volumes: 
      - my_data:/data/db 
  node-web:
    build: .
    depends_on: 
      - database
    environment:
      - DB_HOST=database
    ports: 
      - "3000:3000"
  
volumes: 
  my_data: 