###
GET http://localhost:3000/api/users/healthCheck

###
GET http://localhost:3000/api/users/testing/all

###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "fullName" : "test test",
    "email" : "test@test.com",
    "password": "testPassword"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email" : "test@test.com",
    "password": "testPassword"
}

###
GET http://localhost:3000/api/users/646b6f44689d8e86a2554a1d

###
PUT  http://localhost:3000/api/users/646b6f44689d8e86a2554a1d
Content-Type: application/json

{
    "fullName" : "test tester"
}

###
DELETE  http://localhost:3000/api/users/646b6f44689d8e86a2554a1d