###
GET http://localhost:3000/healthCheck

###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "fullName" : "test test",
    "email" : "test@test.com",
    "password": "testPassword"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "test@test.com",
    "password": "testPassword"
}
