###
GET http://localhost:3000/api/users/healthCheck

###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "fullName" : "test test",
    "email" : "test@test.com",
    "password": "testPassword"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email" : "test@test.com",
    "password": "testPassword"
}

###
GET http://localhost:3000/api/users/646b5af921473d8a26e723bc