apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
      - name: user
        image: docker.io/javaethio/userimage:0.0.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: JWT_SECRET
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: user-db
                key: DB_HOST
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongodb-root-password
          - name: MONGODB_URI
            value: "mongodb://root:$(MONGODB_ROOT_PASSWORD)@mongodb.default.svc.cluster.local:27017/user_test_db?authSource=admin"

